---
- name: Installing commons package for ubuntu
  include_tasks: commons-package-ubuntu.yaml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Installing MySQL Percona Server for Ubuntu
  include_tasks: mysql-server-ubuntu.yaml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Add rule to firewall for MySQL for Ubuntu
  include_tasks: mysql-ufw-cmd.yaml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Copy MySQL User Defined Functions
  copy:
    src: mysql_post_install.sql
    dest: "/tmp/mysql_post_install.sql"
    mode: "0600"

- name: Several useful User Defined Functions (UDF) from Percona Toolkit
  mysql_db:
    name: all
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: import
    target: "/tmp/mysql_post_install.sql"

- name: Select user root to get authentication
  community.mysql.mysql_query:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    query: SELECT count(*) as rows FROM mysql.user u WHERE u.user = %(username)s AND u.authentication_string = %(raw_auth)s
    named_args:
      username: root
      raw_auth: ''
  register: root_has_password

- debug:
    var: root_has_password.query_result[0][0].rows

- name: Update mysql root password for all root accounts
  community.mysql.mysql_user: 
    check_implicit_admin: yes
    name: root 
    password: "{{ mysql.root_password }}"
    host: "{{ item }}" 
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present
  loop:
    - "{{ ansible_host }}"
    - "127.0.0.1"
    - localhost
  when: root_has_password.query_result[0][0].rows | int >= 1