---
- name: Installing commons package
  block:
    - name: MySQL package for Ubuntu
      include_tasks: common/dependencies-ubuntu.yaml
      when: ansible_facts['distribution'] == 'Ubuntu'

- name: Installing Percona MySQL Server
  block:
    - name: Install Percona MySQL Server for Ubuntu
      include_tasks: packages/mysql-server-ubuntu.yaml
      when: ansible_facts['distribution'] == 'Ubuntu'

- name: Add rule to firewall for MySQL
  block:
    - name: Allow MySQL access globaly for Ubuntu
      include_tasks: iptables/mysql-ufw-cmd.yaml
      when: ansible_facts['distribution'] == 'Ubuntu'
