---
- name: "Enable repository"
  command: percona-release enable-only tools

- name: Reload mysql
  ansible.builtin.service:
    name: mysql
    state: reloaded

- name: Restart mysql
  ansible.builtin.service:
    name: mysql
    state: restarted