---
- name: Several useful UDF from Percona Toolkit
  community.mysql.mysql_query:
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    query:
    # - CREATE FUNCTION fnvla_64 RETURNS INTEGER SONAME 'libfnvla_udf.so' # this function not work on ubuntu
    - CREATE FUNCTION fnv_64 RETURNS INTEGER SONAME 'libfnv_udf.so'
    - CREATE FUNCTION murmur_hash RETURNS INTEGER SONAME 'libmurmur_udf.so'
    single_transaction: yes

- name: Removes all anonymous user accounts
  community.mysql.mysql_user:
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: ''
    host_all: yes
    state: absent

- name: Select user root to get authentication
  community.mysql.mysql_query:
    login_unix_socket: "{{ mysqld.socket_login }}"
    login_user: root
    query: SELECT count(*) as rows FROM mysql.user u WHERE u.user = %(username)s AND u.authentication_string = %(raw_auth)s
    named_args:
      username: root
      raw_auth: ''
  register: root_has_password

- name: Update mysql root password for all root accounts
  community.mysql.mysql_user: 
    check_implicit_admin: yes
    name: root 
    password: "{{ mysql.root_password }}"
    host: "{{ item }}" 
    login_unix_socket: "{{ mysqld.socket_login }}"
    state: present
  loop:
    - "127.0.0.1"
    - localhost
  when: root_has_password.query_result[0][0].rows | int >= 1