- name: Set variable on mysqld.cnf
  template:
    src: mysqld.conf.j2
    dest: "{{ mysqld.conf_location }}"
    backup: true
    mode: 0644
  notify:
    - Restart mysql

- name: Create datadir if it does not exist
  file:
    path: "{{ mysqld.data_dir }}"
    state: directory
    owner: "{{ mysqld.mysql_user }}"
    group: "{{ mysqld.mysql_user }}"
    mode: 0755
    setype: mysqld_db_t