---
- name: Add repository XtraBackup
  apt: 
    deb: https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release | lower }}_all.deb
  notify:
    - Enable repository

- name: Update apt cache
  apt: update_cache=yes

- name: Install Percona XtraBackup version {{ xtrabackup.version }}
  apt: 
    pkg: "{{ item }}" 
    state: present
    update_cache: yes
  loop:
    - percona-xtrabackup-{{ xtrabackup.version }}
    - libgcrypt20
    - openssl
    - qpress
    - curl

